// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SeleniumTestBloodPressure
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    // URI for web app being tested
    private String? webAppUri;

    [SetUp]
    public void SetUp()
    {
        webAppUri = Environment.GetEnvironmentVariable("webAppUri");
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void TestBloodPressure()
    {
        driver.Navigate().GoToUrl(webAppUri);
        driver.Manage().Window.Size = new System.Drawing.Size(1022, 842);
        {
            var element = driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .control-label"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .control-label"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .control-label"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector(".form-group:nth-child(1)")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("140");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("139");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("119");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("89");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Diastolic")).Click();
        driver.FindElement(By.Id("BP_Diastolic")).SendKeys("59");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("110");
        driver.FindElement(By.CssSelector(".btn")).Click();
    }
}
