// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SeleniumTest;

[TestClass]
public class SeleniumTestBloodPressure
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    private TestContext testContextInstance;

    // test harness uses this property to initliase test context
    public TestContext TestContext
    {
        get { return testContextInstance; }
        set { testContextInstance = value; }
    }

    // URI for web app being tested
    private string webAppUri;

    [TestInitialize]
    public void SetUp()
    {
        webAppUri = testContextInstance.Properties["webAppUri"].ToString();
        if (string.IsNullOrEmpty(webAppUri))
        {
            throw new ArgumentNullException(nameof(webAppUri), "URL cannot be null.");
        }
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TestCleanup]
    public void TearDown()
    {
        driver.Quit();
    }
    [TestMethod]
    public void TestBloodPressure()
    {
        driver.Navigate().GoToUrl(webAppUri);
        driver.Manage().Window.Size = new System.Drawing.Size(1022, 842);
        {
            var element = driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .control-label"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .control-label"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .control-label"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector(".form-group:nth-child(1)")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("140");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("139");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("119");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("89");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Diastolic")).Click();
        driver.FindElement(By.Id("BP_Diastolic")).SendKeys("59");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("BP_Systolic")).Click();
        driver.FindElement(By.Id("BP_Systolic")).SendKeys("110");
        driver.FindElement(By.CssSelector(".btn")).Click();
    }
}
