 name: Coverage
 
 on:
   workflow_dispatch:
   
 jobs:
   build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore 

    - name: Create Runsettings File
      run: |
          echo "<?xml version='1.0' encoding='utf-8'?>" > coverage.runsettings
          echo "<RunSettings>" >> coverage.runsettings
          echo "  <DataCollectionRunSettings>" >> coverage.runsettings
          echo "    <DataCollectors>" >> coverage.runsettings
          echo "      <DataCollector friendlyName='XPlat Code Coverage'>" >> coverage.runsettings
          echo "        <Configuration>" >> coverage.runsettings
          echo "          <Exclude>[*.SeleniumTest?]*</Exclude>" >> coverage.runsettings
          echo "        </Configuration>" >> coverage.runsettings
          echo "      </DataCollector>" >> coverage.runsettings
          echo "    </DataCollectors>" >> coverage.runsettings
          echo "  </DataCollectionRunSettings>" >> coverage.runsettings
          echo "</RunSettings>" >> coverage.runsettings

    - name: Test
      run: dotnet test --filter "Category=Unit" --no-build --settings coverage.runsettings

    - name: Publish coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: '**/TestResults/**/coverage.cobertura.xml'
        badge: true
        fail_below_min: true
        format: markdown
        indicators: true
        output: both

    - name: Generate Report
      run: reportgenerator \
          -reports:".\**\TestResults\**\coverage.cobertura.xml" \
          -targetdir:"coverage" \
          -reporttypes:Html
