# Sonar cloud scan

name: SonarCloud
on:
  workflow_dispatch:                             

jobs:
  scan_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.organization=sabzero79 \
            -Dsonar.projectKey=SabZero79_bp \
            -Dsonar.login=${{ secrets.SONARCLOUD_SECRET }} \
            -Dsonar.report.export.path=sonar-report.json
            
      - name: Upload SonarCloud Report
        uses: actions/upload-artifact@v3
        with:
          name: sonarcloud-report
          path: sonar-report.json
