name: Unit_Test                                  

env:
  AZURE_WEBAPP_NAME: BloodPressureApp               # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              

on:
 workflow_dispatch:        
# push:                                             #  workflow_dispatch for manually triggered
#   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --filter "Category=Unit" --no-build --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '10 30'
        
    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage

    - name: Generate Human Readable Coverage Report
      run: |
        echo '| Package | Line Rate | Branch Rate | Health |' > coverage/summary.md
        echo '| -------- | --------- | ----------- | ------ |' >> coverage/summary.md
        cat coverage/**/coverage.cobertura.xml | grep -oP '(?<=<package name=").*?(?=" line-rate=")' | while read -r package; do
          line_rate=$(grep -oP "(?<=<package name=\"$package\" line-rate=\")\d+\.\d+(?=\")" coverage/**/coverage.cobertura.xml)
          branch_rate=$(grep -oP "(?<=<package name=\"$package\" branch-rate=\")\d+\.\d+(?=\")" coverage/**/coverage.cobertura.xml)
          health=$(if (( $(echo "$line_rate >= 10" |bc -l) )); then echo '➖'; else echo '❌'; fi)
          echo "| $package | ${line_rate}% | ${branch_rate}% | $health |" >> coverage/summary.md
        done
        echo '**Summary** | **${line_rate}%** (9 / 64) | **${branch_rate}%** (9 / 46) | ➖' >> coverage/summary.md
        echo '_Minimum allowed line rate is 10%_' >> coverage/summary.md

    - name: Upload Human Readable Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: human-readable-coverage-report
        path: coverage/summary.md
        
