name: Unit_Test                                  

env:
  AZURE_WEBAPP_NAME: BloodPressureApp               # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              

on:
 workflow_dispatch:        
# push:                                             #  workflow_dispatch for manually triggered
#   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --filter "Category=Unit" --no-build --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '10 30'
        
    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage

    - name: Generate Human Readable Coverage Report
      run: |
        echo '| Package | Line Rate | Branch Rate | Health |' > coverage/summary.md
        echo '| -------- | --------- | ----------- | ------ |' >> coverage/summary.md
        grep -oP '<package name=".*?" line-rate="\d+\.\d+" branch-rate="\d+\.\d+"' coverage/**/coverage.cobertura.xml | while IFS= read -r line; do
          package=$(echo "$line" | grep -oP '(?<=<package name=").*?(?=")')
          line_rate=$(echo "$line" | grep -oP '(?<=line-rate=")\d+\.\d+(?=")')
          branch_rate=$(echo "$line" | grep -oP '(?<=branch-rate=")\d+\.\d+(?=")')
          line_rate_percentage=$(awk -v rate="$line_rate" 'BEGIN {printf "%d", rate * 100}')
          branch_rate_percentage=$(awk -v rate="$branch_rate" 'BEGIN {printf "%d", rate * 100}')
          health=$(if (( $(echo "$line_rate_percentage >= 10" | bc -l) )); then echo '➖'; else echo '❌'; fi)
          echo "| $package | ${line_rate_percentage}% | ${branch_rate_percentage}% | $health |" >> coverage/summary.md
        done
        total_line_rate=$(grep -oP '(?<=<coverage line-rate=")\d+\.\d+(?=")' coverage/**/coverage.cobertura.xml)
        total_branch_rate=$(grep -oP '(?<=<coverage branch-rate=")\d+\.\d+(?=")' coverage/**/coverage.cobertura.xml)
        total_line_rate_percentage=$(awk -v rate="$total_line_rate" 'BEGIN {printf "%d", rate * 100}')
        total_branch_rate_percentage=$(awk -v rate="$total_branch_rate" 'BEGIN {printf "%d", rate * 100}')
        echo '**Summary** | **${total_line_rate_percentage}%** (N/A) | **${total_branch_rate_percentage}%** (N/A) | ➖' >> coverage/summary.md
        echo '_Minimum allowed line rate is 10%_' >> coverage/summary.md

    - name: Upload Human Readable Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: human-readable-coverage-report
        path: coverage/summary.md
